FROM rust:1.33-slim

LABEL maintainer="Anthony Josiah Dodd <adodd@docql.io>"
EXPOSE 8080
WORKDIR /api

# Add a few system deps.
RUN apt-get update && apt-get install -y make pkg-config libssl-dev && \
    rustup target add wasm32-unknown-unknown && \
    cargo install cargo-make

COPY ./client client
COPY ./common common
COPY ./server server
COPY ./static static
COPY ./Makefile.toml Makefile.toml
COPY ./Cargo.toml Cargo.toml
COPY ./Cargo.lock Cargo.lock

ENTRYPOINT ["cargo", "make"]
